// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ffProto.proto

/*
Package ffProto is a generated protocol buffer package.

It is generated from these files:
	ffProto.proto

It has these top-level messages:
	StDeviceInfo
	StAccountData
	StTeamMember
	MsgKeepAlive
	MsgServerRegister
	MsgPrepareLoginPlatformUniqueId
	MsgLoginPlatformUniqueId
	MsgLoginPlatformSidToken
	MsgReLogin
	MsgKick
	MsgEnterGameWorld
	MsgAgentDisConnect
	MsgEnterTeam
	MsgInviteJoinTeam
	MsgAnswerJoinTeam
	MsgLeaveTeam
	MsgEnterMatchServer
	MsgLeaveMatchServer
	MsgStartMatch
	MsgStopMatch
	MsgMatchResult
*/
package ffProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_KeepAlive                    MessageType = 0
	MessageType_ServerRegister               MessageType = 1
	MessageType_PrepareLoginPlatformUniqueId MessageType = 2
	MessageType_LoginPlatformUniqueId        MessageType = 3
	MessageType_LoginPlatformSidToken        MessageType = 4
	MessageType_ReLogin                      MessageType = 5
	MessageType_Kick                         MessageType = 6
	MessageType_EnterGameWorld               MessageType = 7
	MessageType_AgentDisConnect              MessageType = 8
	MessageType_EnterTeam                    MessageType = 9
	MessageType_InviteJoinTeam               MessageType = 10
	MessageType_AnswerJoinTeam               MessageType = 11
	MessageType_LeaveTeam                    MessageType = 12
	MessageType_EnterMatchServer             MessageType = 13
	MessageType_LeaveMatchServer             MessageType = 14
	MessageType_StartMatch                   MessageType = 15
	MessageType_StopMatch                    MessageType = 16
	MessageType_MatchResult                  MessageType = 17
)

var MessageType_name = map[int32]string{
	0:  "KeepAlive",
	1:  "ServerRegister",
	2:  "PrepareLoginPlatformUniqueId",
	3:  "LoginPlatformUniqueId",
	4:  "LoginPlatformSidToken",
	5:  "ReLogin",
	6:  "Kick",
	7:  "EnterGameWorld",
	8:  "AgentDisConnect",
	9:  "EnterTeam",
	10: "InviteJoinTeam",
	11: "AnswerJoinTeam",
	12: "LeaveTeam",
	13: "EnterMatchServer",
	14: "LeaveMatchServer",
	15: "StartMatch",
	16: "StopMatch",
	17: "MatchResult",
}
var MessageType_value = map[string]int32{
	"KeepAlive":                    0,
	"ServerRegister":               1,
	"PrepareLoginPlatformUniqueId": 2,
	"LoginPlatformUniqueId":        3,
	"LoginPlatformSidToken":        4,
	"ReLogin":                      5,
	"Kick":                         6,
	"EnterGameWorld":               7,
	"AgentDisConnect":              8,
	"EnterTeam":                    9,
	"InviteJoinTeam":               10,
	"AnswerJoinTeam":               11,
	"LeaveTeam":                    12,
	"EnterMatchServer":             13,
	"LeaveMatchServer":             14,
	"StartMatch":                   15,
	"StopMatch":                    16,
	"MatchResult":                  17,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Generated by the msggen.py message compiler.
type StDeviceInfo struct {
	DeviceGUID            string `protobuf:"bytes,1,opt,name=deviceGUID" json:"deviceGUID,omitempty"`
	DeviceType            string `protobuf:"bytes,2,opt,name=deviceType" json:"deviceType,omitempty"`
	OperatingSystem       string `protobuf:"bytes,3,opt,name=operatingSystem" json:"operatingSystem,omitempty"`
	OperatingSystemFamily string `protobuf:"bytes,4,opt,name=operatingSystemFamily" json:"operatingSystemFamily,omitempty"`
	ProcessorType         string `protobuf:"bytes,5,opt,name=processorType" json:"processorType,omitempty"`
	ProcessorFrequency    int32  `protobuf:"varint,6,opt,name=processorFrequency" json:"processorFrequency,omitempty"`
	ProcessorCount        int32  `protobuf:"varint,7,opt,name=processorCount" json:"processorCount,omitempty"`
	SystemMemorySize      int32  `protobuf:"varint,8,opt,name=systemMemorySize" json:"systemMemorySize,omitempty"`
	GraphicsMemorySize    int32  `protobuf:"varint,9,opt,name=graphicsMemorySize" json:"graphicsMemorySize,omitempty"`
}

func (m *StDeviceInfo) Reset()                    { *m = StDeviceInfo{} }
func (m *StDeviceInfo) String() string            { return proto.CompactTextString(m) }
func (*StDeviceInfo) ProtoMessage()               {}
func (*StDeviceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StDeviceInfo) GetDeviceGUID() string {
	if m != nil {
		return m.DeviceGUID
	}
	return ""
}

func (m *StDeviceInfo) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *StDeviceInfo) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

func (m *StDeviceInfo) GetOperatingSystemFamily() string {
	if m != nil {
		return m.OperatingSystemFamily
	}
	return ""
}

func (m *StDeviceInfo) GetProcessorType() string {
	if m != nil {
		return m.ProcessorType
	}
	return ""
}

func (m *StDeviceInfo) GetProcessorFrequency() int32 {
	if m != nil {
		return m.ProcessorFrequency
	}
	return 0
}

func (m *StDeviceInfo) GetProcessorCount() int32 {
	if m != nil {
		return m.ProcessorCount
	}
	return 0
}

func (m *StDeviceInfo) GetSystemMemorySize() int32 {
	if m != nil {
		return m.SystemMemorySize
	}
	return 0
}

func (m *StDeviceInfo) GetGraphicsMemorySize() int32 {
	if m != nil {
		return m.GraphicsMemorySize
	}
	return 0
}

type StAccountData struct {
	IsFresh    bool    `protobuf:"varint,1,opt,name=isFresh" json:"isFresh,omitempty"`
	ServerTime int32   `protobuf:"varint,2,opt,name=serverTime" json:"serverTime,omitempty"`
	ServerZone int32   `protobuf:"varint,3,opt,name=serverZone" json:"serverZone,omitempty"`
	Name       string  `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	BaseKeys   []int32 `protobuf:"varint,5,rep,packed,name=baseKeys" json:"baseKeys,omitempty"`
	BaseDatas  []int32 `protobuf:"varint,6,rep,packed,name=baseDatas" json:"baseDatas,omitempty"`
}

func (m *StAccountData) Reset()                    { *m = StAccountData{} }
func (m *StAccountData) String() string            { return proto.CompactTextString(m) }
func (*StAccountData) ProtoMessage()               {}
func (*StAccountData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StAccountData) GetIsFresh() bool {
	if m != nil {
		return m.IsFresh
	}
	return false
}

func (m *StAccountData) GetServerTime() int32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *StAccountData) GetServerZone() int32 {
	if m != nil {
		return m.ServerZone
	}
	return 0
}

func (m *StAccountData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StAccountData) GetBaseKeys() []int32 {
	if m != nil {
		return m.BaseKeys
	}
	return nil
}

func (m *StAccountData) GetBaseDatas() []int32 {
	if m != nil {
		return m.BaseDatas
	}
	return nil
}

type StTeamMember struct {
	Player     string  `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
	ServerTime int32   `protobuf:"varint,2,opt,name=serverTime" json:"serverTime,omitempty"`
	ServerZone int32   `protobuf:"varint,3,opt,name=serverZone" json:"serverZone,omitempty"`
	Name       string  `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	BaseKeys   []int32 `protobuf:"varint,5,rep,packed,name=baseKeys" json:"baseKeys,omitempty"`
	BaseDatas  []int32 `protobuf:"varint,6,rep,packed,name=baseDatas" json:"baseDatas,omitempty"`
}

func (m *StTeamMember) Reset()                    { *m = StTeamMember{} }
func (m *StTeamMember) String() string            { return proto.CompactTextString(m) }
func (*StTeamMember) ProtoMessage()               {}
func (*StTeamMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StTeamMember) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

func (m *StTeamMember) GetServerTime() int32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *StTeamMember) GetServerZone() int32 {
	if m != nil {
		return m.ServerZone
	}
	return 0
}

func (m *StTeamMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StTeamMember) GetBaseKeys() []int32 {
	if m != nil {
		return m.BaseKeys
	}
	return nil
}

func (m *StTeamMember) GetBaseDatas() []int32 {
	if m != nil {
		return m.BaseDatas
	}
	return nil
}

type MsgKeepAlive struct {
	Number int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *MsgKeepAlive) Reset()                    { *m = MsgKeepAlive{} }
func (m *MsgKeepAlive) String() string            { return proto.CompactTextString(m) }
func (*MsgKeepAlive) ProtoMessage()               {}
func (*MsgKeepAlive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgKeepAlive) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type MsgServerRegister struct {
	ServerType string `protobuf:"bytes,1,opt,name=serverType" json:"serverType,omitempty"`
	ServerID   int32  `protobuf:"varint,2,opt,name=serverID" json:"serverID,omitempty"`
	Result     int32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgServerRegister) Reset()                    { *m = MsgServerRegister{} }
func (m *MsgServerRegister) String() string            { return proto.CompactTextString(m) }
func (*MsgServerRegister) ProtoMessage()               {}
func (*MsgServerRegister) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MsgServerRegister) GetServerType() string {
	if m != nil {
		return m.ServerType
	}
	return ""
}

func (m *MsgServerRegister) GetServerID() int32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *MsgServerRegister) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgPrepareLoginPlatformUniqueId struct {
	SubChannel        string `protobuf:"bytes,1,opt,name=subChannel" json:"subChannel,omitempty"`
	UUIDPlatformBound string `protobuf:"bytes,2,opt,name=UUIDPlatformBound" json:"UUIDPlatformBound,omitempty"`
	UUIDPlatformLogin string `protobuf:"bytes,3,opt,name=UUIDPlatformLogin" json:"UUIDPlatformLogin,omitempty"`
	RandomSalt        string `protobuf:"bytes,4,opt,name=randomSalt" json:"randomSalt,omitempty"`
	Timestamp         int32  `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	FixSalt           int32  `protobuf:"varint,6,opt,name=fixSalt" json:"fixSalt,omitempty"`
	Status            int32  `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`
	Result            int32  `protobuf:"varint,8,opt,name=result" json:"result,omitempty"`
}

func (m *MsgPrepareLoginPlatformUniqueId) Reset()                    { *m = MsgPrepareLoginPlatformUniqueId{} }
func (m *MsgPrepareLoginPlatformUniqueId) String() string            { return proto.CompactTextString(m) }
func (*MsgPrepareLoginPlatformUniqueId) ProtoMessage()               {}
func (*MsgPrepareLoginPlatformUniqueId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MsgPrepareLoginPlatformUniqueId) GetSubChannel() string {
	if m != nil {
		return m.SubChannel
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueId) GetUUIDPlatformBound() string {
	if m != nil {
		return m.UUIDPlatformBound
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueId) GetUUIDPlatformLogin() string {
	if m != nil {
		return m.UUIDPlatformLogin
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueId) GetRandomSalt() string {
	if m != nil {
		return m.RandomSalt
	}
	return ""
}

func (m *MsgPrepareLoginPlatformUniqueId) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsgPrepareLoginPlatformUniqueId) GetFixSalt() int32 {
	if m != nil {
		return m.FixSalt
	}
	return 0
}

func (m *MsgPrepareLoginPlatformUniqueId) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MsgPrepareLoginPlatformUniqueId) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgLoginPlatformUniqueId struct {
	TokenCustom string        `protobuf:"bytes,1,opt,name=tokenCustom" json:"tokenCustom,omitempty"`
	DeviceInfo  *StDeviceInfo `protobuf:"bytes,2,opt,name=deviceInfo" json:"deviceInfo,omitempty"`
	UUIDLogin   uint64        `protobuf:"varint,3,opt,name=UUIDLogin" json:"UUIDLogin,omitempty"`
	Result      int32         `protobuf:"varint,4,opt,name=result" json:"result,omitempty"`
}

func (m *MsgLoginPlatformUniqueId) Reset()                    { *m = MsgLoginPlatformUniqueId{} }
func (m *MsgLoginPlatformUniqueId) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginPlatformUniqueId) ProtoMessage()               {}
func (*MsgLoginPlatformUniqueId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MsgLoginPlatformUniqueId) GetTokenCustom() string {
	if m != nil {
		return m.TokenCustom
	}
	return ""
}

func (m *MsgLoginPlatformUniqueId) GetDeviceInfo() *StDeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *MsgLoginPlatformUniqueId) GetUUIDLogin() uint64 {
	if m != nil {
		return m.UUIDLogin
	}
	return 0
}

func (m *MsgLoginPlatformUniqueId) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgLoginPlatformSidToken struct {
	TokenPlatform string        `protobuf:"bytes,1,opt,name=tokenPlatform" json:"tokenPlatform,omitempty"`
	DeviceInfo    *StDeviceInfo `protobuf:"bytes,2,opt,name=deviceInfo" json:"deviceInfo,omitempty"`
	UUIDLogin     uint64        `protobuf:"varint,3,opt,name=UUIDLogin" json:"UUIDLogin,omitempty"`
	Result        int32         `protobuf:"varint,4,opt,name=result" json:"result,omitempty"`
}

func (m *MsgLoginPlatformSidToken) Reset()                    { *m = MsgLoginPlatformSidToken{} }
func (m *MsgLoginPlatformSidToken) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginPlatformSidToken) ProtoMessage()               {}
func (*MsgLoginPlatformSidToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MsgLoginPlatformSidToken) GetTokenPlatform() string {
	if m != nil {
		return m.TokenPlatform
	}
	return ""
}

func (m *MsgLoginPlatformSidToken) GetDeviceInfo() *StDeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *MsgLoginPlatformSidToken) GetUUIDLogin() uint64 {
	if m != nil {
		return m.UUIDLogin
	}
	return 0
}

func (m *MsgLoginPlatformSidToken) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgReLogin struct {
	CheckData  string        `protobuf:"bytes,1,opt,name=checkData" json:"checkData,omitempty"`
	DeviceInfo *StDeviceInfo `protobuf:"bytes,2,opt,name=deviceInfo" json:"deviceInfo,omitempty"`
	Result     int32         `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgReLogin) Reset()                    { *m = MsgReLogin{} }
func (m *MsgReLogin) String() string            { return proto.CompactTextString(m) }
func (*MsgReLogin) ProtoMessage()               {}
func (*MsgReLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MsgReLogin) GetCheckData() string {
	if m != nil {
		return m.CheckData
	}
	return ""
}

func (m *MsgReLogin) GetDeviceInfo() *StDeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *MsgReLogin) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgKick struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *MsgKick) Reset()                    { *m = MsgKick{} }
func (m *MsgKick) String() string            { return proto.CompactTextString(m) }
func (*MsgKick) ProtoMessage()               {}
func (*MsgKick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MsgKick) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgEnterGameWorld struct {
	ServerID  int32  `protobuf:"varint,1,opt,name=serverID" json:"serverID,omitempty"`
	UUIDLogin uint64 `protobuf:"varint,2,opt,name=UUIDLogin" json:"UUIDLogin,omitempty"`
	Result    int32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgEnterGameWorld) Reset()                    { *m = MsgEnterGameWorld{} }
func (m *MsgEnterGameWorld) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterGameWorld) ProtoMessage()               {}
func (*MsgEnterGameWorld) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MsgEnterGameWorld) GetServerID() int32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *MsgEnterGameWorld) GetUUIDLogin() uint64 {
	if m != nil {
		return m.UUIDLogin
	}
	return 0
}

func (m *MsgEnterGameWorld) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgAgentDisConnect struct {
}

func (m *MsgAgentDisConnect) Reset()                    { *m = MsgAgentDisConnect{} }
func (m *MsgAgentDisConnect) String() string            { return proto.CompactTextString(m) }
func (*MsgAgentDisConnect) ProtoMessage()               {}
func (*MsgAgentDisConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type MsgEnterTeam struct {
	Teamid int32 `protobuf:"varint,1,opt,name=teamid" json:"teamid,omitempty"`
}

func (m *MsgEnterTeam) Reset()                    { *m = MsgEnterTeam{} }
func (m *MsgEnterTeam) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterTeam) ProtoMessage()               {}
func (*MsgEnterTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MsgEnterTeam) GetTeamid() int32 {
	if m != nil {
		return m.Teamid
	}
	return 0
}

type MsgInviteJoinTeam struct {
	UUIDTarget uint64 `protobuf:"varint,1,opt,name=UUIDTarget" json:"UUIDTarget,omitempty"`
	Result     int32  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
}

func (m *MsgInviteJoinTeam) Reset()                    { *m = MsgInviteJoinTeam{} }
func (m *MsgInviteJoinTeam) String() string            { return proto.CompactTextString(m) }
func (*MsgInviteJoinTeam) ProtoMessage()               {}
func (*MsgInviteJoinTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MsgInviteJoinTeam) GetUUIDTarget() uint64 {
	if m != nil {
		return m.UUIDTarget
	}
	return 0
}

func (m *MsgInviteJoinTeam) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgAnswerJoinTeam struct {
	InvitePlayer string `protobuf:"bytes,1,opt,name=invitePlayer" json:"invitePlayer,omitempty"`
	Join         bool   `protobuf:"varint,2,opt,name=join" json:"join,omitempty"`
	Result       int32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgAnswerJoinTeam) Reset()                    { *m = MsgAnswerJoinTeam{} }
func (m *MsgAnswerJoinTeam) String() string            { return proto.CompactTextString(m) }
func (*MsgAnswerJoinTeam) ProtoMessage()               {}
func (*MsgAnswerJoinTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MsgAnswerJoinTeam) GetInvitePlayer() string {
	if m != nil {
		return m.InvitePlayer
	}
	return ""
}

func (m *MsgAnswerJoinTeam) GetJoin() bool {
	if m != nil {
		return m.Join
	}
	return false
}

func (m *MsgAnswerJoinTeam) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgLeaveTeam struct {
}

func (m *MsgLeaveTeam) Reset()                    { *m = MsgLeaveTeam{} }
func (m *MsgLeaveTeam) String() string            { return proto.CompactTextString(m) }
func (*MsgLeaveTeam) ProtoMessage()               {}
func (*MsgLeaveTeam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type MsgEnterMatchServer struct {
	UUIDAccount uint64 `protobuf:"varint,1,opt,name=UUIDAccount" json:"UUIDAccount,omitempty"`
	UUIDTeam    uint64 `protobuf:"varint,2,opt,name=UUIDTeam" json:"UUIDTeam,omitempty"`
	Result      int32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgEnterMatchServer) Reset()                    { *m = MsgEnterMatchServer{} }
func (m *MsgEnterMatchServer) String() string            { return proto.CompactTextString(m) }
func (*MsgEnterMatchServer) ProtoMessage()               {}
func (*MsgEnterMatchServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *MsgEnterMatchServer) GetUUIDAccount() uint64 {
	if m != nil {
		return m.UUIDAccount
	}
	return 0
}

func (m *MsgEnterMatchServer) GetUUIDTeam() uint64 {
	if m != nil {
		return m.UUIDTeam
	}
	return 0
}

func (m *MsgEnterMatchServer) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgLeaveMatchServer struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *MsgLeaveMatchServer) Reset()                    { *m = MsgLeaveMatchServer{} }
func (m *MsgLeaveMatchServer) String() string            { return proto.CompactTextString(m) }
func (*MsgLeaveMatchServer) ProtoMessage()               {}
func (*MsgLeaveMatchServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *MsgLeaveMatchServer) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgStartMatch struct {
	MatchMode int32 `protobuf:"varint,1,opt,name=MatchMode" json:"MatchMode,omitempty"`
	Stranger  int32 `protobuf:"varint,2,opt,name=Stranger" json:"Stranger,omitempty"`
	Result    int32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgStartMatch) Reset()                    { *m = MsgStartMatch{} }
func (m *MsgStartMatch) String() string            { return proto.CompactTextString(m) }
func (*MsgStartMatch) ProtoMessage()               {}
func (*MsgStartMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *MsgStartMatch) GetMatchMode() int32 {
	if m != nil {
		return m.MatchMode
	}
	return 0
}

func (m *MsgStartMatch) GetStranger() int32 {
	if m != nil {
		return m.Stranger
	}
	return 0
}

func (m *MsgStartMatch) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgStopMatch struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *MsgStopMatch) Reset()                    { *m = MsgStopMatch{} }
func (m *MsgStopMatch) String() string            { return proto.CompactTextString(m) }
func (*MsgStopMatch) ProtoMessage()               {}
func (*MsgStopMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *MsgStopMatch) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MsgMatchResult struct {
	Addr   string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Token  uint64 `protobuf:"varint,2,opt,name=token" json:"token,omitempty"`
	Result int32  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *MsgMatchResult) Reset()                    { *m = MsgMatchResult{} }
func (m *MsgMatchResult) String() string            { return proto.CompactTextString(m) }
func (*MsgMatchResult) ProtoMessage()               {}
func (*MsgMatchResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MsgMatchResult) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *MsgMatchResult) GetToken() uint64 {
	if m != nil {
		return m.Token
	}
	return 0
}

func (m *MsgMatchResult) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*StDeviceInfo)(nil), "StDeviceInfo")
	proto.RegisterType((*StAccountData)(nil), "StAccountData")
	proto.RegisterType((*StTeamMember)(nil), "StTeamMember")
	proto.RegisterType((*MsgKeepAlive)(nil), "MsgKeepAlive")
	proto.RegisterType((*MsgServerRegister)(nil), "MsgServerRegister")
	proto.RegisterType((*MsgPrepareLoginPlatformUniqueId)(nil), "MsgPrepareLoginPlatformUniqueId")
	proto.RegisterType((*MsgLoginPlatformUniqueId)(nil), "MsgLoginPlatformUniqueId")
	proto.RegisterType((*MsgLoginPlatformSidToken)(nil), "MsgLoginPlatformSidToken")
	proto.RegisterType((*MsgReLogin)(nil), "MsgReLogin")
	proto.RegisterType((*MsgKick)(nil), "MsgKick")
	proto.RegisterType((*MsgEnterGameWorld)(nil), "MsgEnterGameWorld")
	proto.RegisterType((*MsgAgentDisConnect)(nil), "MsgAgentDisConnect")
	proto.RegisterType((*MsgEnterTeam)(nil), "MsgEnterTeam")
	proto.RegisterType((*MsgInviteJoinTeam)(nil), "MsgInviteJoinTeam")
	proto.RegisterType((*MsgAnswerJoinTeam)(nil), "MsgAnswerJoinTeam")
	proto.RegisterType((*MsgLeaveTeam)(nil), "MsgLeaveTeam")
	proto.RegisterType((*MsgEnterMatchServer)(nil), "MsgEnterMatchServer")
	proto.RegisterType((*MsgLeaveMatchServer)(nil), "MsgLeaveMatchServer")
	proto.RegisterType((*MsgStartMatch)(nil), "MsgStartMatch")
	proto.RegisterType((*MsgStopMatch)(nil), "MsgStopMatch")
	proto.RegisterType((*MsgMatchResult)(nil), "MsgMatchResult")
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("ffProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1025 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5d, 0x6e, 0x23, 0xc5,
	0x13, 0xff, 0xdb, 0xb1, 0x13, 0xa7, 0x1c, 0x3b, 0x93, 0xde, 0xec, 0x5f, 0x03, 0x5a, 0x2d, 0xc1,
	0x42, 0xab, 0x68, 0xc5, 0xe6, 0x01, 0xb8, 0x40, 0x88, 0xc9, 0xca, 0x64, 0x47, 0x8a, 0xc6, 0x89,
	0x90, 0x78, 0xeb, 0x8c, 0x2b, 0x93, 0x26, 0x9e, 0x6e, 0xa7, 0xbb, 0x1d, 0x30, 0x27, 0xe0, 0x1a,
	0x3c, 0x70, 0x03, 0x24, 0xee, 0xc4, 0x29, 0x50, 0xf5, 0xf4, 0x7c, 0x39, 0x31, 0x12, 0x2f, 0x88,
	0x17, 0xab, 0xeb, 0x57, 0xd5, 0x5d, 0xbf, 0xfa, 0x1c, 0xc3, 0xe0, 0xf6, 0xf6, 0x52, 0x2b, 0xab,
	0x4e, 0x16, 0xf4, 0x3b, 0xfa, 0x65, 0x0b, 0xf6, 0xa6, 0x76, 0x8c, 0x8f, 0x22, 0xc1, 0x89, 0xbc,
	0x55, 0xec, 0x35, 0xc0, 0xcc, 0x49, 0xef, 0xaf, 0x27, 0xe3, 0xb0, 0x75, 0xd4, 0x3a, 0xde, 0x8d,
	0x6b, 0x48, 0xa5, 0xbf, 0x5a, 0x2d, 0x30, 0x6c, 0xd7, 0xf5, 0x84, 0xb0, 0x63, 0xd8, 0x57, 0x0b,
	0xd4, 0xdc, 0x0a, 0x99, 0x4e, 0x57, 0xc6, 0x62, 0x16, 0x6e, 0x39, 0xa3, 0x75, 0x98, 0x7d, 0x05,
	0x2f, 0xd7, 0xa0, 0x73, 0x9e, 0x89, 0xf9, 0x2a, 0xec, 0x38, 0xfb, 0xe7, 0x95, 0xec, 0x33, 0x18,
	0x2c, 0xb4, 0x4a, 0xd0, 0x18, 0xa5, 0x1d, 0x85, 0xae, 0xb3, 0x6e, 0x82, 0xec, 0x04, 0x58, 0x09,
	0x9c, 0x6b, 0x7c, 0x58, 0xa2, 0x4c, 0x56, 0xe1, 0xf6, 0x51, 0xeb, 0xb8, 0x1b, 0x3f, 0xa3, 0x61,
	0x6f, 0x60, 0x58, 0xa2, 0x67, 0x6a, 0x29, 0x6d, 0xb8, 0xe3, 0x6c, 0xd7, 0x50, 0xf6, 0x16, 0x02,
	0xe3, 0xd8, 0x44, 0x98, 0x29, 0xbd, 0x9a, 0x8a, 0x9f, 0x31, 0xec, 0x39, 0xcb, 0x27, 0x38, 0x71,
	0x48, 0x35, 0x5f, 0xdc, 0x89, 0xc4, 0xd4, 0xac, 0x77, 0x73, 0x0e, 0x4f, 0x35, 0xa3, 0x3f, 0x5a,
	0x30, 0x98, 0xda, 0xd3, 0x24, 0x21, 0x4f, 0x63, 0x6e, 0x39, 0x0b, 0x61, 0x47, 0x98, 0x73, 0x8d,
	0xe6, 0xce, 0x15, 0xa2, 0x17, 0x17, 0x22, 0x55, 0xc1, 0xa0, 0x7e, 0x44, 0x7d, 0x25, 0xb2, 0xbc,
	0x0a, 0xdd, 0xb8, 0x86, 0x54, 0xfa, 0xef, 0x95, 0x44, 0x57, 0x80, 0x52, 0x4f, 0x08, 0x63, 0xd0,
	0x91, 0x3c, 0x43, 0x9f, 0x6a, 0x77, 0x66, 0x1f, 0x43, 0xef, 0x86, 0x1b, 0xbc, 0xc0, 0x95, 0x09,
	0xbb, 0x47, 0x5b, 0xc7, 0xdd, 0xb8, 0x94, 0xd9, 0x2b, 0xd8, 0xa5, 0x33, 0xb1, 0x32, 0xe1, 0xb6,
	0x53, 0x56, 0xc0, 0xe8, 0xf7, 0x16, 0x35, 0xd1, 0x15, 0x72, 0x0a, 0xff, 0x06, 0x35, 0xfb, 0x3f,
	0x6c, 0x2f, 0xe6, 0x7c, 0x85, 0xda, 0x37, 0x90, 0x97, 0xfe, 0x63, 0xb4, 0xdf, 0xc0, 0x5e, 0x64,
	0xd2, 0x0b, 0xc4, 0xc5, 0xe9, 0x5c, 0x3c, 0x22, 0xb1, 0x96, 0x4b, 0xe2, 0xef, 0x58, 0x77, 0x63,
	0x2f, 0x8d, 0x52, 0x38, 0x88, 0x4c, 0x3a, 0x75, 0x34, 0x62, 0x4c, 0x85, 0xb1, 0x8d, 0x50, 0xa8,
	0x09, 0xfd, 0x9c, 0x54, 0x08, 0xd1, 0xca, 0xa5, 0xc9, 0xd8, 0x07, 0x5a, 0xca, 0xe4, 0x48, 0xa3,
	0x59, 0xce, 0xad, 0x0f, 0xd1, 0x4b, 0xa3, 0xdf, 0xda, 0xf0, 0x49, 0x64, 0xd2, 0x4b, 0x8d, 0x0b,
	0xae, 0xf1, 0x83, 0x4a, 0x85, 0xbc, 0x9c, 0x73, 0x7b, 0xab, 0x74, 0x76, 0x2d, 0xc5, 0xc3, 0x12,
	0x27, 0x33, 0xe7, 0x77, 0x79, 0x73, 0x76, 0xc7, 0xa5, 0xc4, 0x79, 0xe9, 0xb7, 0x44, 0xd8, 0xe7,
	0x70, 0x70, 0x7d, 0x3d, 0x19, 0x17, 0xf7, 0xbe, 0x56, 0x4b, 0x39, 0xf3, 0x63, 0xfa, 0x54, 0xb1,
	0x6e, 0xed, 0x5c, 0xfa, 0x79, 0x7d, 0xaa, 0x20, 0xdf, 0x9a, 0xcb, 0x99, 0xca, 0xa6, 0x7c, 0x6e,
	0x7d, 0x11, 0x6a, 0x08, 0xa5, 0xdb, 0x8a, 0x0c, 0x8d, 0xe5, 0xd9, 0xc2, 0xcd, 0x65, 0x37, 0xae,
	0x00, 0xea, 0xe6, 0x5b, 0xf1, 0x93, 0xbb, 0x9a, 0x0f, 0x62, 0x21, 0x52, 0x3e, 0x8c, 0xe5, 0x76,
	0x69, 0xfc, 0xd4, 0x79, 0xa9, 0x96, 0xa7, 0x5e, 0x23, 0x4f, 0xbf, 0xb6, 0x20, 0x8c, 0x4c, 0xfa,
	0x7c, 0x82, 0x8e, 0xa0, 0x6f, 0xd5, 0x3d, 0xca, 0xb3, 0xa5, 0xb1, 0x2a, 0xf3, 0x19, 0xaa, 0x43,
	0xec, 0x5d, 0xb1, 0xc2, 0x68, 0xe1, 0xb9, 0xdc, 0xf4, 0xbf, 0x18, 0x9c, 0xd4, 0xb7, 0x60, 0x5c,
	0x33, 0xa0, 0xa8, 0x28, 0x15, 0x55, 0x6e, 0x3a, 0x71, 0x05, 0xd4, 0x38, 0x76, 0x9a, 0xb5, 0x7c,
	0x86, 0xe3, 0x54, 0xcc, 0xae, 0x88, 0x07, 0x2d, 0x31, 0x47, 0xa8, 0x50, 0x78, 0x96, 0x4d, 0xf0,
	0xdf, 0xe1, 0xf9, 0x00, 0x10, 0x99, 0x34, 0xce, 0xbb, 0x8d, 0xde, 0x48, 0xee, 0x30, 0xb9, 0xa7,
	0x01, 0xf1, 0xa4, 0x2a, 0xe0, 0x9f, 0x12, 0xda, 0xd4, 0xe6, 0x9f, 0xc2, 0x0e, 0xcd, 0x9d, 0x48,
	0xee, 0x6b, 0x26, 0xad, 0x86, 0x09, 0xba, 0x91, 0xfb, 0x46, 0x5a, 0xd4, 0xef, 0x79, 0x86, 0xdf,
	0x29, 0x3d, 0x9f, 0x35, 0x46, 0xaa, 0xb5, 0x36, 0x52, 0x8d, 0xe0, 0xdb, 0x9b, 0x83, 0x6f, 0x32,
	0x39, 0x04, 0x16, 0x99, 0xf4, 0x34, 0x45, 0x69, 0xc7, 0xc2, 0x9c, 0x29, 0x29, 0x31, 0xb1, 0x7e,
	0x2f, 0x38, 0xe7, 0xb4, 0xd3, 0xe8, 0xb6, 0x45, 0x9e, 0x89, 0x59, 0x41, 0x32, 0x97, 0x46, 0x17,
	0x8e, 0xe4, 0x44, 0x3e, 0x0a, 0x8b, 0xdf, 0x2a, 0x21, 0x9d, 0xf1, 0x6b, 0x00, 0xf2, 0x7b, 0xc5,
	0x75, 0x8a, 0x79, 0x54, 0x9d, 0xb8, 0x86, 0xd4, 0xa8, 0xb4, 0x1b, 0x54, 0x12, 0xf7, 0xd8, 0xa9,
	0x34, 0x3f, 0xa2, 0x2e, 0x1f, 0x1b, 0xc1, 0x9e, 0x70, 0xcf, 0x5f, 0xd6, 0xb7, 0x69, 0x03, 0xa3,
	0x9d, 0xf8, 0x83, 0xf2, 0x41, 0xf7, 0x62, 0x77, 0xde, 0x18, 0xef, 0xd0, 0x45, 0xf6, 0x01, 0xf9,
	0x23, 0xd2, 0xfb, 0xa3, 0x7b, 0x78, 0x51, 0x44, 0x1a, 0x71, 0x9b, 0xdc, 0xe5, 0x3b, 0x8e, 0x46,
	0x88, 0x18, 0xfb, 0x4f, 0x91, 0x0f, 0xa2, 0x0e, 0x51, 0x29, 0x5c, 0x4c, 0xc8, 0x33, 0x9f, 0xed,
	0x52, 0xde, 0xe8, 0xfc, 0x9d, 0x73, 0xe6, 0x9c, 0xd7, 0x9d, 0x6d, 0x6a, 0x01, 0x0e, 0x03, 0xda,
	0xba, 0x96, 0x6b, 0xeb, 0xcc, 0xa9, 0xc4, 0xee, 0x10, 0xa9, 0x19, 0x7a, 0xdb, 0x0a, 0x20, 0x46,
	0x53, 0xab, 0xb9, 0x4c, 0x51, 0x17, 0xfb, 0xb6, 0x90, 0x37, 0x32, 0xca, 0x0b, 0x3d, 0xb5, 0x6a,
	0x91, 0x7b, 0xd8, 0x44, 0x25, 0x86, 0x61, 0x64, 0x52, 0x67, 0x13, 0x3b, 0x84, 0x92, 0xce, 0x67,
	0xb3, 0xa2, 0x20, 0xee, 0xcc, 0x0e, 0xa1, 0xeb, 0xe6, 0xd7, 0x27, 0x24, 0x17, 0x36, 0xf9, 0x7e,
	0xfb, 0x67, 0x1b, 0xfa, 0x11, 0x1a, 0xc3, 0xd3, 0xfc, 0x7f, 0xd3, 0x00, 0x76, 0xcb, 0x2f, 0x51,
	0xf0, 0x3f, 0xc6, 0x60, 0xd8, 0xfc, 0xe0, 0x04, 0x2d, 0x76, 0x04, 0xaf, 0xfe, 0xee, 0xd3, 0x10,
	0xb4, 0xd9, 0x47, 0xf0, 0xf2, 0x79, 0xd5, 0xd6, 0x13, 0x55, 0xb1, 0x8b, 0x82, 0x0e, 0xeb, 0xc3,
	0x8e, 0x9f, 0xff, 0xa0, 0xcb, 0x7a, 0xd0, 0xa1, 0xc9, 0x0c, 0xb6, 0x89, 0x42, 0x73, 0x00, 0x83,
	0x1d, 0xf6, 0x02, 0xf6, 0xd7, 0xa6, 0x25, 0xe8, 0x11, 0xf5, 0x72, 0x58, 0x82, 0x5d, 0xba, 0xd7,
	0x9c, 0x89, 0x00, 0x08, 0x6b, 0xb6, 0x76, 0xd0, 0xa7, 0x6b, 0x65, 0x27, 0x06, 0x7b, 0xec, 0x10,
	0x82, 0xf5, 0x46, 0x0c, 0x06, 0x84, 0xae, 0x77, 0x4c, 0x30, 0x64, 0x43, 0x80, 0xaa, 0x31, 0x82,
	0x7d, 0x7a, 0xaa, 0xac, 0x62, 0x10, 0xb0, 0x7d, 0xe8, 0xd7, 0x8a, 0x15, 0x1c, 0xdc, 0x6c, 0xbb,
	0x3f, 0xbb, 0x5f, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x52, 0x0b, 0xa5, 0xfd, 0x0a, 0x00,
	0x00,
}
