// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Config.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	Config.proto

It has these top-level messages:
	Grammar
	Asset
	ExcelExportTest
	Item
	Language
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Grammar struct {
	Grammar string `protobuf:"bytes,1,opt,name=grammar" json:"grammar,omitempty"`
}

func (m *Grammar) Reset()                    { *m = Grammar{} }
func (m *Grammar) String() string            { return proto.CompactTextString(m) }
func (*Grammar) ProtoMessage()               {}
func (*Grammar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Grammar) GetGrammar() string {
	if m != nil {
		return m.Grammar
	}
	return ""
}

type Asset struct {
	AssetsKey   []int32           `protobuf:"varint,1,rep,packed,name=AssetsKey" json:"AssetsKey,omitempty"`
	AssetsValue []*Asset_StAssets `protobuf:"bytes,2,rep,name=AssetsValue" json:"AssetsValue,omitempty"`
}

func (m *Asset) Reset()                    { *m = Asset{} }
func (m *Asset) String() string            { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()               {}
func (*Asset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Asset) GetAssetsKey() []int32 {
	if m != nil {
		return m.AssetsKey
	}
	return nil
}

func (m *Asset) GetAssetsValue() []*Asset_StAssets {
	if m != nil {
		return m.AssetsValue
	}
	return nil
}

type Asset_StAssets struct {
	BattleDefault string `protobuf:"bytes,1,opt,name=BattleDefault" json:"BattleDefault,omitempty"`
	HomeDefault   string `protobuf:"bytes,2,opt,name=HomeDefault" json:"HomeDefault,omitempty"`
}

func (m *Asset_StAssets) Reset()                    { *m = Asset_StAssets{} }
func (m *Asset_StAssets) String() string            { return proto.CompactTextString(m) }
func (*Asset_StAssets) ProtoMessage()               {}
func (*Asset_StAssets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Asset_StAssets) GetBattleDefault() string {
	if m != nil {
		return m.BattleDefault
	}
	return ""
}

func (m *Asset_StAssets) GetHomeDefault() string {
	if m != nil {
		return m.HomeDefault
	}
	return ""
}

type ExcelExportTest struct {
	VIPmapKey   []int32                      `protobuf:"varint,1,rep,packed,name=VIPmapKey" json:"VIPmapKey,omitempty"`
	VIPmapValue []*ExcelExportTest_StVIPmap  `protobuf:"bytes,2,rep,name=VIPmapValue" json:"VIPmapValue,omitempty"`
	VIPstruct   *ExcelExportTest_StVIPstruct `protobuf:"bytes,3,opt,name=VIPstruct" json:"VIPstruct,omitempty"`
	VIPlist     []*ExcelExportTest_StVIPlist `protobuf:"bytes,4,rep,name=VIPlist" json:"VIPlist,omitempty"`
}

func (m *ExcelExportTest) Reset()                    { *m = ExcelExportTest{} }
func (m *ExcelExportTest) String() string            { return proto.CompactTextString(m) }
func (*ExcelExportTest) ProtoMessage()               {}
func (*ExcelExportTest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ExcelExportTest) GetVIPmapKey() []int32 {
	if m != nil {
		return m.VIPmapKey
	}
	return nil
}

func (m *ExcelExportTest) GetVIPmapValue() []*ExcelExportTest_StVIPmap {
	if m != nil {
		return m.VIPmapValue
	}
	return nil
}

func (m *ExcelExportTest) GetVIPstruct() *ExcelExportTest_StVIPstruct {
	if m != nil {
		return m.VIPstruct
	}
	return nil
}

func (m *ExcelExportTest) GetVIPlist() []*ExcelExportTest_StVIPlist {
	if m != nil {
		return m.VIPlist
	}
	return nil
}

type ExcelExportTest_StVIPmap struct {
	InfoInt32        int32    `protobuf:"varint,1,opt,name=InfoInt32" json:"InfoInt32,omitempty"`
	InfoInt64        int64    `protobuf:"varint,2,opt,name=InfoInt64" json:"InfoInt64,omitempty"`
	InfoStr          string   `protobuf:"bytes,3,opt,name=InfoStr" json:"InfoStr,omitempty"`
	InfoInt32Array   []int32  `protobuf:"varint,4,rep,packed,name=InfoInt32Array" json:"InfoInt32Array,omitempty"`
	InfoInt64Array   []int64  `protobuf:"varint,5,rep,packed,name=InfoInt64Array" json:"InfoInt64Array,omitempty"`
	InfoStringArray  []string `protobuf:"bytes,6,rep,name=InfoStringArray" json:"InfoStringArray,omitempty"`
	ItemClientID     int32    `protobuf:"varint,7,opt,name=ItemClientID" json:"ItemClientID,omitempty"`
	Consume          *Grammar `protobuf:"bytes,8,opt,name=Consume" json:"Consume,omitempty"`
	EmptyInt32       int32    `protobuf:"varint,9,opt,name=EmptyInt32" json:"EmptyInt32,omitempty"`
	EmptyInt64       int64    `protobuf:"varint,10,opt,name=EmptyInt64" json:"EmptyInt64,omitempty"`
	EmptyStr         string   `protobuf:"bytes,11,opt,name=EmptyStr" json:"EmptyStr,omitempty"`
	EmptyInt32Array  []int32  `protobuf:"varint,12,rep,packed,name=EmptyInt32Array" json:"EmptyInt32Array,omitempty"`
	EmptyInt64Array  []int64  `protobuf:"varint,13,rep,packed,name=EmptyInt64Array" json:"EmptyInt64Array,omitempty"`
	EmptyStringArray []string `protobuf:"bytes,14,rep,name=EmptyStringArray" json:"EmptyStringArray,omitempty"`
}

func (m *ExcelExportTest_StVIPmap) Reset()                    { *m = ExcelExportTest_StVIPmap{} }
func (m *ExcelExportTest_StVIPmap) String() string            { return proto.CompactTextString(m) }
func (*ExcelExportTest_StVIPmap) ProtoMessage()               {}
func (*ExcelExportTest_StVIPmap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *ExcelExportTest_StVIPmap) GetInfoInt32() int32 {
	if m != nil {
		return m.InfoInt32
	}
	return 0
}

func (m *ExcelExportTest_StVIPmap) GetInfoInt64() int64 {
	if m != nil {
		return m.InfoInt64
	}
	return 0
}

func (m *ExcelExportTest_StVIPmap) GetInfoStr() string {
	if m != nil {
		return m.InfoStr
	}
	return ""
}

func (m *ExcelExportTest_StVIPmap) GetInfoInt32Array() []int32 {
	if m != nil {
		return m.InfoInt32Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPmap) GetInfoInt64Array() []int64 {
	if m != nil {
		return m.InfoInt64Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPmap) GetInfoStringArray() []string {
	if m != nil {
		return m.InfoStringArray
	}
	return nil
}

func (m *ExcelExportTest_StVIPmap) GetItemClientID() int32 {
	if m != nil {
		return m.ItemClientID
	}
	return 0
}

func (m *ExcelExportTest_StVIPmap) GetConsume() *Grammar {
	if m != nil {
		return m.Consume
	}
	return nil
}

func (m *ExcelExportTest_StVIPmap) GetEmptyInt32() int32 {
	if m != nil {
		return m.EmptyInt32
	}
	return 0
}

func (m *ExcelExportTest_StVIPmap) GetEmptyInt64() int64 {
	if m != nil {
		return m.EmptyInt64
	}
	return 0
}

func (m *ExcelExportTest_StVIPmap) GetEmptyStr() string {
	if m != nil {
		return m.EmptyStr
	}
	return ""
}

func (m *ExcelExportTest_StVIPmap) GetEmptyInt32Array() []int32 {
	if m != nil {
		return m.EmptyInt32Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPmap) GetEmptyInt64Array() []int64 {
	if m != nil {
		return m.EmptyInt64Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPmap) GetEmptyStringArray() []string {
	if m != nil {
		return m.EmptyStringArray
	}
	return nil
}

type ExcelExportTest_StVIPstruct struct {
	InfoInt32        int32    `protobuf:"varint,1,opt,name=InfoInt32" json:"InfoInt32,omitempty"`
	InfoInt64        int64    `protobuf:"varint,2,opt,name=InfoInt64" json:"InfoInt64,omitempty"`
	InfoStr          string   `protobuf:"bytes,3,opt,name=InfoStr" json:"InfoStr,omitempty"`
	InfoInt32Array   []int32  `protobuf:"varint,4,rep,packed,name=InfoInt32Array" json:"InfoInt32Array,omitempty"`
	InfoInt64Array   []int64  `protobuf:"varint,5,rep,packed,name=InfoInt64Array" json:"InfoInt64Array,omitempty"`
	InfoStringArray  []string `protobuf:"bytes,6,rep,name=InfoStringArray" json:"InfoStringArray,omitempty"`
	ItemClientID     int32    `protobuf:"varint,7,opt,name=ItemClientID" json:"ItemClientID,omitempty"`
	Consume          *Grammar `protobuf:"bytes,8,opt,name=Consume" json:"Consume,omitempty"`
	EmptyInt32       int32    `protobuf:"varint,9,opt,name=EmptyInt32" json:"EmptyInt32,omitempty"`
	EmptyInt64       int64    `protobuf:"varint,10,opt,name=EmptyInt64" json:"EmptyInt64,omitempty"`
	EmptyStr         string   `protobuf:"bytes,11,opt,name=EmptyStr" json:"EmptyStr,omitempty"`
	EmptyInt32Array  []int32  `protobuf:"varint,12,rep,packed,name=EmptyInt32Array" json:"EmptyInt32Array,omitempty"`
	EmptyInt64Array  []int64  `protobuf:"varint,13,rep,packed,name=EmptyInt64Array" json:"EmptyInt64Array,omitempty"`
	EmptyStringArray []string `protobuf:"bytes,14,rep,name=EmptyStringArray" json:"EmptyStringArray,omitempty"`
}

func (m *ExcelExportTest_StVIPstruct) Reset()                    { *m = ExcelExportTest_StVIPstruct{} }
func (m *ExcelExportTest_StVIPstruct) String() string            { return proto.CompactTextString(m) }
func (*ExcelExportTest_StVIPstruct) ProtoMessage()               {}
func (*ExcelExportTest_StVIPstruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *ExcelExportTest_StVIPstruct) GetInfoInt32() int32 {
	if m != nil {
		return m.InfoInt32
	}
	return 0
}

func (m *ExcelExportTest_StVIPstruct) GetInfoInt64() int64 {
	if m != nil {
		return m.InfoInt64
	}
	return 0
}

func (m *ExcelExportTest_StVIPstruct) GetInfoStr() string {
	if m != nil {
		return m.InfoStr
	}
	return ""
}

func (m *ExcelExportTest_StVIPstruct) GetInfoInt32Array() []int32 {
	if m != nil {
		return m.InfoInt32Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPstruct) GetInfoInt64Array() []int64 {
	if m != nil {
		return m.InfoInt64Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPstruct) GetInfoStringArray() []string {
	if m != nil {
		return m.InfoStringArray
	}
	return nil
}

func (m *ExcelExportTest_StVIPstruct) GetItemClientID() int32 {
	if m != nil {
		return m.ItemClientID
	}
	return 0
}

func (m *ExcelExportTest_StVIPstruct) GetConsume() *Grammar {
	if m != nil {
		return m.Consume
	}
	return nil
}

func (m *ExcelExportTest_StVIPstruct) GetEmptyInt32() int32 {
	if m != nil {
		return m.EmptyInt32
	}
	return 0
}

func (m *ExcelExportTest_StVIPstruct) GetEmptyInt64() int64 {
	if m != nil {
		return m.EmptyInt64
	}
	return 0
}

func (m *ExcelExportTest_StVIPstruct) GetEmptyStr() string {
	if m != nil {
		return m.EmptyStr
	}
	return ""
}

func (m *ExcelExportTest_StVIPstruct) GetEmptyInt32Array() []int32 {
	if m != nil {
		return m.EmptyInt32Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPstruct) GetEmptyInt64Array() []int64 {
	if m != nil {
		return m.EmptyInt64Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPstruct) GetEmptyStringArray() []string {
	if m != nil {
		return m.EmptyStringArray
	}
	return nil
}

type ExcelExportTest_StVIPlist struct {
	InfoInt32        int32    `protobuf:"varint,1,opt,name=InfoInt32" json:"InfoInt32,omitempty"`
	InfoInt64        int64    `protobuf:"varint,2,opt,name=InfoInt64" json:"InfoInt64,omitempty"`
	InfoStr          string   `protobuf:"bytes,3,opt,name=InfoStr" json:"InfoStr,omitempty"`
	InfoInt32Array   []int32  `protobuf:"varint,4,rep,packed,name=InfoInt32Array" json:"InfoInt32Array,omitempty"`
	InfoInt64Array   []int64  `protobuf:"varint,5,rep,packed,name=InfoInt64Array" json:"InfoInt64Array,omitempty"`
	InfoStringArray  []string `protobuf:"bytes,6,rep,name=InfoStringArray" json:"InfoStringArray,omitempty"`
	ItemClientID     int32    `protobuf:"varint,7,opt,name=ItemClientID" json:"ItemClientID,omitempty"`
	Consume          *Grammar `protobuf:"bytes,8,opt,name=Consume" json:"Consume,omitempty"`
	EmptyInt32       int32    `protobuf:"varint,9,opt,name=EmptyInt32" json:"EmptyInt32,omitempty"`
	EmptyInt64       int64    `protobuf:"varint,10,opt,name=EmptyInt64" json:"EmptyInt64,omitempty"`
	EmptyStr         string   `protobuf:"bytes,11,opt,name=EmptyStr" json:"EmptyStr,omitempty"`
	EmptyInt32Array  []int32  `protobuf:"varint,12,rep,packed,name=EmptyInt32Array" json:"EmptyInt32Array,omitempty"`
	EmptyInt64Array  []int64  `protobuf:"varint,13,rep,packed,name=EmptyInt64Array" json:"EmptyInt64Array,omitempty"`
	EmptyStringArray []string `protobuf:"bytes,14,rep,name=EmptyStringArray" json:"EmptyStringArray,omitempty"`
}

func (m *ExcelExportTest_StVIPlist) Reset()                    { *m = ExcelExportTest_StVIPlist{} }
func (m *ExcelExportTest_StVIPlist) String() string            { return proto.CompactTextString(m) }
func (*ExcelExportTest_StVIPlist) ProtoMessage()               {}
func (*ExcelExportTest_StVIPlist) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *ExcelExportTest_StVIPlist) GetInfoInt32() int32 {
	if m != nil {
		return m.InfoInt32
	}
	return 0
}

func (m *ExcelExportTest_StVIPlist) GetInfoInt64() int64 {
	if m != nil {
		return m.InfoInt64
	}
	return 0
}

func (m *ExcelExportTest_StVIPlist) GetInfoStr() string {
	if m != nil {
		return m.InfoStr
	}
	return ""
}

func (m *ExcelExportTest_StVIPlist) GetInfoInt32Array() []int32 {
	if m != nil {
		return m.InfoInt32Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPlist) GetInfoInt64Array() []int64 {
	if m != nil {
		return m.InfoInt64Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPlist) GetInfoStringArray() []string {
	if m != nil {
		return m.InfoStringArray
	}
	return nil
}

func (m *ExcelExportTest_StVIPlist) GetItemClientID() int32 {
	if m != nil {
		return m.ItemClientID
	}
	return 0
}

func (m *ExcelExportTest_StVIPlist) GetConsume() *Grammar {
	if m != nil {
		return m.Consume
	}
	return nil
}

func (m *ExcelExportTest_StVIPlist) GetEmptyInt32() int32 {
	if m != nil {
		return m.EmptyInt32
	}
	return 0
}

func (m *ExcelExportTest_StVIPlist) GetEmptyInt64() int64 {
	if m != nil {
		return m.EmptyInt64
	}
	return 0
}

func (m *ExcelExportTest_StVIPlist) GetEmptyStr() string {
	if m != nil {
		return m.EmptyStr
	}
	return ""
}

func (m *ExcelExportTest_StVIPlist) GetEmptyInt32Array() []int32 {
	if m != nil {
		return m.EmptyInt32Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPlist) GetEmptyInt64Array() []int64 {
	if m != nil {
		return m.EmptyInt64Array
	}
	return nil
}

func (m *ExcelExportTest_StVIPlist) GetEmptyStringArray() []string {
	if m != nil {
		return m.EmptyStringArray
	}
	return nil
}

type Item struct {
	ItemTemplateKey   []int32                `protobuf:"varint,1,rep,packed,name=ItemTemplateKey" json:"ItemTemplateKey,omitempty"`
	ItemTemplateValue []*Item_StItemTemplate `protobuf:"bytes,2,rep,name=ItemTemplateValue" json:"ItemTemplateValue,omitempty"`
	GunWeaponKey      []int32                `protobuf:"varint,3,rep,packed,name=GunWeaponKey" json:"GunWeaponKey,omitempty"`
	GunWeaponValue    []*Item_StGunWeapon    `protobuf:"bytes,4,rep,name=GunWeaponValue" json:"GunWeaponValue,omitempty"`
	AmmunitionKey     []int32                `protobuf:"varint,5,rep,packed,name=AmmunitionKey" json:"AmmunitionKey,omitempty"`
	AmmunitionValue   []*Item_StAmmunition   `protobuf:"bytes,6,rep,name=AmmunitionValue" json:"AmmunitionValue,omitempty"`
	AttachmentKey     []int32                `protobuf:"varint,7,rep,packed,name=AttachmentKey" json:"AttachmentKey,omitempty"`
	AttachmentValue   []*Item_StAttachment   `protobuf:"bytes,8,rep,name=AttachmentValue" json:"AttachmentValue,omitempty"`
	MelleeWeaponKey   []int32                `protobuf:"varint,9,rep,packed,name=MelleeWeaponKey" json:"MelleeWeaponKey,omitempty"`
	MelleeWeaponValue []*Item_StMelleeWeapon `protobuf:"bytes,10,rep,name=MelleeWeaponValue" json:"MelleeWeaponValue,omitempty"`
	EquipmentKey      []int32                `protobuf:"varint,11,rep,packed,name=EquipmentKey" json:"EquipmentKey,omitempty"`
	EquipmentValue    []*Item_StEquipment    `protobuf:"bytes,12,rep,name=EquipmentValue" json:"EquipmentValue,omitempty"`
	ConsumableKey     []int32                `protobuf:"varint,13,rep,packed,name=ConsumableKey" json:"ConsumableKey,omitempty"`
	ConsumableValue   []*Item_StConsumable   `protobuf:"bytes,14,rep,name=ConsumableValue" json:"ConsumableValue,omitempty"`
	ThrowableKey      []int32                `protobuf:"varint,15,rep,packed,name=ThrowableKey" json:"ThrowableKey,omitempty"`
	ThrowableValue    []*Item_StThrowable    `protobuf:"bytes,16,rep,name=ThrowableValue" json:"ThrowableValue,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Item) GetItemTemplateKey() []int32 {
	if m != nil {
		return m.ItemTemplateKey
	}
	return nil
}

func (m *Item) GetItemTemplateValue() []*Item_StItemTemplate {
	if m != nil {
		return m.ItemTemplateValue
	}
	return nil
}

func (m *Item) GetGunWeaponKey() []int32 {
	if m != nil {
		return m.GunWeaponKey
	}
	return nil
}

func (m *Item) GetGunWeaponValue() []*Item_StGunWeapon {
	if m != nil {
		return m.GunWeaponValue
	}
	return nil
}

func (m *Item) GetAmmunitionKey() []int32 {
	if m != nil {
		return m.AmmunitionKey
	}
	return nil
}

func (m *Item) GetAmmunitionValue() []*Item_StAmmunition {
	if m != nil {
		return m.AmmunitionValue
	}
	return nil
}

func (m *Item) GetAttachmentKey() []int32 {
	if m != nil {
		return m.AttachmentKey
	}
	return nil
}

func (m *Item) GetAttachmentValue() []*Item_StAttachment {
	if m != nil {
		return m.AttachmentValue
	}
	return nil
}

func (m *Item) GetMelleeWeaponKey() []int32 {
	if m != nil {
		return m.MelleeWeaponKey
	}
	return nil
}

func (m *Item) GetMelleeWeaponValue() []*Item_StMelleeWeapon {
	if m != nil {
		return m.MelleeWeaponValue
	}
	return nil
}

func (m *Item) GetEquipmentKey() []int32 {
	if m != nil {
		return m.EquipmentKey
	}
	return nil
}

func (m *Item) GetEquipmentValue() []*Item_StEquipment {
	if m != nil {
		return m.EquipmentValue
	}
	return nil
}

func (m *Item) GetConsumableKey() []int32 {
	if m != nil {
		return m.ConsumableKey
	}
	return nil
}

func (m *Item) GetConsumableValue() []*Item_StConsumable {
	if m != nil {
		return m.ConsumableValue
	}
	return nil
}

func (m *Item) GetThrowableKey() []int32 {
	if m != nil {
		return m.ThrowableKey
	}
	return nil
}

func (m *Item) GetThrowableValue() []*Item_StThrowable {
	if m != nil {
		return m.ThrowableValue
	}
	return nil
}

type Item_StItemTemplate struct {
	Name       string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Desc       string `protobuf:"bytes,2,opt,name=Desc" json:"Desc,omitempty"`
	AssetID    int32  `protobuf:"varint,3,opt,name=AssetID" json:"AssetID,omitempty"`
	IconNormal string `protobuf:"bytes,4,opt,name=IconNormal" json:"IconNormal,omitempty"`
	IconLarge  string `protobuf:"bytes,5,opt,name=IconLarge" json:"IconLarge,omitempty"`
	ItemType   int32  `protobuf:"varint,6,opt,name=ItemType" json:"ItemType,omitempty"`
}

func (m *Item_StItemTemplate) Reset()                    { *m = Item_StItemTemplate{} }
func (m *Item_StItemTemplate) String() string            { return proto.CompactTextString(m) }
func (*Item_StItemTemplate) ProtoMessage()               {}
func (*Item_StItemTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *Item_StItemTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item_StItemTemplate) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Item_StItemTemplate) GetAssetID() int32 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

func (m *Item_StItemTemplate) GetIconNormal() string {
	if m != nil {
		return m.IconNormal
	}
	return ""
}

func (m *Item_StItemTemplate) GetIconLarge() string {
	if m != nil {
		return m.IconLarge
	}
	return ""
}

func (m *Item_StItemTemplate) GetItemType() int32 {
	if m != nil {
		return m.ItemType
	}
	return 0
}

type Item_StGunWeapon struct {
	GunWeaponType   int32           `protobuf:"varint,1,opt,name=GunWeaponType" json:"GunWeaponType,omitempty"`
	ShootMode       []int32         `protobuf:"varint,2,rep,packed,name=ShootMode" json:"ShootMode,omitempty"`
	AmmunitionType  int32           `protobuf:"varint,3,opt,name=AmmunitionType" json:"AmmunitionType,omitempty"`
	AttachmentTypes []int32         `protobuf:"varint,4,rep,packed,name=AttachmentTypes" json:"AttachmentTypes,omitempty"`
	Attrs           map[int32]int32 `protobuf:"bytes,5,rep,name=Attrs" json:"Attrs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AttrsKey        []int32         `protobuf:"varint,6,rep,packed,name=AttrsKey" json:"AttrsKey,omitempty"`
	AttrsValue      []int32         `protobuf:"varint,7,rep,packed,name=AttrsValue" json:"AttrsValue,omitempty"`
}

func (m *Item_StGunWeapon) Reset()                    { *m = Item_StGunWeapon{} }
func (m *Item_StGunWeapon) String() string            { return proto.CompactTextString(m) }
func (*Item_StGunWeapon) ProtoMessage()               {}
func (*Item_StGunWeapon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 1} }

func (m *Item_StGunWeapon) GetGunWeaponType() int32 {
	if m != nil {
		return m.GunWeaponType
	}
	return 0
}

func (m *Item_StGunWeapon) GetShootMode() []int32 {
	if m != nil {
		return m.ShootMode
	}
	return nil
}

func (m *Item_StGunWeapon) GetAmmunitionType() int32 {
	if m != nil {
		return m.AmmunitionType
	}
	return 0
}

func (m *Item_StGunWeapon) GetAttachmentTypes() []int32 {
	if m != nil {
		return m.AttachmentTypes
	}
	return nil
}

func (m *Item_StGunWeapon) GetAttrs() map[int32]int32 {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Item_StGunWeapon) GetAttrsKey() []int32 {
	if m != nil {
		return m.AttrsKey
	}
	return nil
}

func (m *Item_StGunWeapon) GetAttrsValue() []int32 {
	if m != nil {
		return m.AttrsValue
	}
	return nil
}

type Item_StAmmunition struct {
	AmmunitionType  int32 `protobuf:"varint,1,opt,name=AmmunitionType" json:"AmmunitionType,omitempty"`
	AmmunitionStack int32 `protobuf:"varint,2,opt,name=AmmunitionStack" json:"AmmunitionStack,omitempty"`
}

func (m *Item_StAmmunition) Reset()                    { *m = Item_StAmmunition{} }
func (m *Item_StAmmunition) String() string            { return proto.CompactTextString(m) }
func (*Item_StAmmunition) ProtoMessage()               {}
func (*Item_StAmmunition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 2} }

func (m *Item_StAmmunition) GetAmmunitionType() int32 {
	if m != nil {
		return m.AmmunitionType
	}
	return 0
}

func (m *Item_StAmmunition) GetAmmunitionStack() int32 {
	if m != nil {
		return m.AmmunitionStack
	}
	return 0
}

type Item_StAttachment struct {
	AttachmentType int32           `protobuf:"varint,1,opt,name=AttachmentType" json:"AttachmentType,omitempty"`
	GunWeapons     []int32         `protobuf:"varint,2,rep,packed,name=GunWeapons" json:"GunWeapons,omitempty"`
	ShutSound      int32           `protobuf:"varint,3,opt,name=ShutSound" json:"ShutSound,omitempty"`
	ShutFire       int32           `protobuf:"varint,4,opt,name=ShutFire" json:"ShutFire,omitempty"`
	Attrs          map[int32]int32 `protobuf:"bytes,5,rep,name=Attrs" json:"Attrs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AttrsKey       []int32         `protobuf:"varint,6,rep,packed,name=AttrsKey" json:"AttrsKey,omitempty"`
	AttrsValue     []int32         `protobuf:"varint,7,rep,packed,name=AttrsValue" json:"AttrsValue,omitempty"`
	Clip           map[int32]int32 `protobuf:"bytes,8,rep,name=Clip" json:"Clip,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClipKey        []int32         `protobuf:"varint,9,rep,packed,name=ClipKey" json:"ClipKey,omitempty"`
	ClipValue      []int32         `protobuf:"varint,10,rep,packed,name=ClipValue" json:"ClipValue,omitempty"`
}

func (m *Item_StAttachment) Reset()                    { *m = Item_StAttachment{} }
func (m *Item_StAttachment) String() string            { return proto.CompactTextString(m) }
func (*Item_StAttachment) ProtoMessage()               {}
func (*Item_StAttachment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 3} }

func (m *Item_StAttachment) GetAttachmentType() int32 {
	if m != nil {
		return m.AttachmentType
	}
	return 0
}

func (m *Item_StAttachment) GetGunWeapons() []int32 {
	if m != nil {
		return m.GunWeapons
	}
	return nil
}

func (m *Item_StAttachment) GetShutSound() int32 {
	if m != nil {
		return m.ShutSound
	}
	return 0
}

func (m *Item_StAttachment) GetShutFire() int32 {
	if m != nil {
		return m.ShutFire
	}
	return 0
}

func (m *Item_StAttachment) GetAttrs() map[int32]int32 {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Item_StAttachment) GetAttrsKey() []int32 {
	if m != nil {
		return m.AttrsKey
	}
	return nil
}

func (m *Item_StAttachment) GetAttrsValue() []int32 {
	if m != nil {
		return m.AttrsValue
	}
	return nil
}

func (m *Item_StAttachment) GetClip() map[int32]int32 {
	if m != nil {
		return m.Clip
	}
	return nil
}

func (m *Item_StAttachment) GetClipKey() []int32 {
	if m != nil {
		return m.ClipKey
	}
	return nil
}

func (m *Item_StAttachment) GetClipValue() []int32 {
	if m != nil {
		return m.ClipValue
	}
	return nil
}

type Item_StMelleeWeapon struct {
	MelleeWeaponType int32           `protobuf:"varint,1,opt,name=MelleeWeaponType" json:"MelleeWeaponType,omitempty"`
	Attrs            map[int32]int32 `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AttrsKey         []int32         `protobuf:"varint,3,rep,packed,name=AttrsKey" json:"AttrsKey,omitempty"`
	AttrsValue       []int32         `protobuf:"varint,4,rep,packed,name=AttrsValue" json:"AttrsValue,omitempty"`
}

func (m *Item_StMelleeWeapon) Reset()                    { *m = Item_StMelleeWeapon{} }
func (m *Item_StMelleeWeapon) String() string            { return proto.CompactTextString(m) }
func (*Item_StMelleeWeapon) ProtoMessage()               {}
func (*Item_StMelleeWeapon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 4} }

func (m *Item_StMelleeWeapon) GetMelleeWeaponType() int32 {
	if m != nil {
		return m.MelleeWeaponType
	}
	return 0
}

func (m *Item_StMelleeWeapon) GetAttrs() map[int32]int32 {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Item_StMelleeWeapon) GetAttrsKey() []int32 {
	if m != nil {
		return m.AttrsKey
	}
	return nil
}

func (m *Item_StMelleeWeapon) GetAttrsValue() []int32 {
	if m != nil {
		return m.AttrsValue
	}
	return nil
}

type Item_StEquipment struct {
	EquipmentType int32           `protobuf:"varint,1,opt,name=EquipmentType" json:"EquipmentType,omitempty"`
	Attrs         map[int32]int32 `protobuf:"bytes,2,rep,name=Attrs" json:"Attrs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AttrsKey      []int32         `protobuf:"varint,3,rep,packed,name=AttrsKey" json:"AttrsKey,omitempty"`
	AttrsValue    []int32         `protobuf:"varint,4,rep,packed,name=AttrsValue" json:"AttrsValue,omitempty"`
}

func (m *Item_StEquipment) Reset()                    { *m = Item_StEquipment{} }
func (m *Item_StEquipment) String() string            { return proto.CompactTextString(m) }
func (*Item_StEquipment) ProtoMessage()               {}
func (*Item_StEquipment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 5} }

func (m *Item_StEquipment) GetEquipmentType() int32 {
	if m != nil {
		return m.EquipmentType
	}
	return 0
}

func (m *Item_StEquipment) GetAttrs() map[int32]int32 {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Item_StEquipment) GetAttrsKey() []int32 {
	if m != nil {
		return m.AttrsKey
	}
	return nil
}

func (m *Item_StEquipment) GetAttrsValue() []int32 {
	if m != nil {
		return m.AttrsValue
	}
	return nil
}

type Item_StConsumable struct {
	ConsumableType      int32 `protobuf:"varint,1,opt,name=ConsumableType" json:"ConsumableType,omitempty"`
	UseTime             int32 `protobuf:"varint,2,opt,name=UseTime" json:"UseTime,omitempty"`
	UseHpLimit          int32 `protobuf:"varint,3,opt,name=UseHpLimit" json:"UseHpLimit,omitempty"`
	UseRecover          int32 `protobuf:"varint,4,opt,name=UseRecover" json:"UseRecover,omitempty"`
	UseRecoverUpLimit   int32 `protobuf:"varint,5,opt,name=UseRecoverUpLimit" json:"UseRecoverUpLimit,omitempty"`
	KeepTime            int32 `protobuf:"varint,6,opt,name=KeepTime" json:"KeepTime,omitempty"`
	KeepRecoverInterval int32 `protobuf:"varint,7,opt,name=KeepRecoverInterval" json:"KeepRecoverInterval,omitempty"`
	KeepRecover         int32 `protobuf:"varint,8,opt,name=KeepRecover" json:"KeepRecover,omitempty"`
}

func (m *Item_StConsumable) Reset()                    { *m = Item_StConsumable{} }
func (m *Item_StConsumable) String() string            { return proto.CompactTextString(m) }
func (*Item_StConsumable) ProtoMessage()               {}
func (*Item_StConsumable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 6} }

func (m *Item_StConsumable) GetConsumableType() int32 {
	if m != nil {
		return m.ConsumableType
	}
	return 0
}

func (m *Item_StConsumable) GetUseTime() int32 {
	if m != nil {
		return m.UseTime
	}
	return 0
}

func (m *Item_StConsumable) GetUseHpLimit() int32 {
	if m != nil {
		return m.UseHpLimit
	}
	return 0
}

func (m *Item_StConsumable) GetUseRecover() int32 {
	if m != nil {
		return m.UseRecover
	}
	return 0
}

func (m *Item_StConsumable) GetUseRecoverUpLimit() int32 {
	if m != nil {
		return m.UseRecoverUpLimit
	}
	return 0
}

func (m *Item_StConsumable) GetKeepTime() int32 {
	if m != nil {
		return m.KeepTime
	}
	return 0
}

func (m *Item_StConsumable) GetKeepRecoverInterval() int32 {
	if m != nil {
		return m.KeepRecoverInterval
	}
	return 0
}

func (m *Item_StConsumable) GetKeepRecover() int32 {
	if m != nil {
		return m.KeepRecover
	}
	return 0
}

type Item_StThrowable struct {
	ThrowableType int32 `protobuf:"varint,1,opt,name=ThrowableType" json:"ThrowableType,omitempty"`
	RadiusClose   int32 `protobuf:"varint,2,opt,name=RadiusClose" json:"RadiusClose,omitempty"`
}

func (m *Item_StThrowable) Reset()                    { *m = Item_StThrowable{} }
func (m *Item_StThrowable) String() string            { return proto.CompactTextString(m) }
func (*Item_StThrowable) ProtoMessage()               {}
func (*Item_StThrowable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 7} }

func (m *Item_StThrowable) GetThrowableType() int32 {
	if m != nil {
		return m.ThrowableType
	}
	return 0
}

func (m *Item_StThrowable) GetRadiusClose() int32 {
	if m != nil {
		return m.RadiusClose
	}
	return 0
}

type Language struct {
	CommonKey   []string              `protobuf:"bytes,1,rep,name=CommonKey" json:"CommonKey,omitempty"`
	CommonValue []*Language_StCommon  `protobuf:"bytes,2,rep,name=CommonValue" json:"CommonValue,omitempty"`
	Special     []*Language_StSpecial `protobuf:"bytes,3,rep,name=Special" json:"Special,omitempty"`
	ErrorKey    []string              `protobuf:"bytes,4,rep,name=ErrorKey" json:"ErrorKey,omitempty"`
	ErrorValue  []*Language_StError   `protobuf:"bytes,5,rep,name=ErrorValue" json:"ErrorValue,omitempty"`
}

func (m *Language) Reset()                    { *m = Language{} }
func (m *Language) String() string            { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()               {}
func (*Language) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Language) GetCommonKey() []string {
	if m != nil {
		return m.CommonKey
	}
	return nil
}

func (m *Language) GetCommonValue() []*Language_StCommon {
	if m != nil {
		return m.CommonValue
	}
	return nil
}

func (m *Language) GetSpecial() []*Language_StSpecial {
	if m != nil {
		return m.Special
	}
	return nil
}

func (m *Language) GetErrorKey() []string {
	if m != nil {
		return m.ErrorKey
	}
	return nil
}

func (m *Language) GetErrorValue() []*Language_StError {
	if m != nil {
		return m.ErrorValue
	}
	return nil
}

type Language_StCommon struct {
	Value string `protobuf:"bytes,1,opt,name=Value" json:"Value,omitempty"`
}

func (m *Language_StCommon) Reset()                    { *m = Language_StCommon{} }
func (m *Language_StCommon) String() string            { return proto.CompactTextString(m) }
func (*Language_StCommon) ProtoMessage()               {}
func (*Language_StCommon) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *Language_StCommon) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Language_StSpecial struct {
	Value string `protobuf:"bytes,1,opt,name=Value" json:"Value,omitempty"`
}

func (m *Language_StSpecial) Reset()                    { *m = Language_StSpecial{} }
func (m *Language_StSpecial) String() string            { return proto.CompactTextString(m) }
func (*Language_StSpecial) ProtoMessage()               {}
func (*Language_StSpecial) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 1} }

func (m *Language_StSpecial) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Language_StError struct {
	Value string `protobuf:"bytes,1,opt,name=Value" json:"Value,omitempty"`
}

func (m *Language_StError) Reset()                    { *m = Language_StError{} }
func (m *Language_StError) String() string            { return proto.CompactTextString(m) }
func (*Language_StError) ProtoMessage()               {}
func (*Language_StError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 2} }

func (m *Language_StError) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Grammar)(nil), "main.Grammar")
	proto.RegisterType((*Asset)(nil), "main.Asset")
	proto.RegisterType((*Asset_StAssets)(nil), "main.Asset.StAssets")
	proto.RegisterType((*ExcelExportTest)(nil), "main.ExcelExportTest")
	proto.RegisterType((*ExcelExportTest_StVIPmap)(nil), "main.ExcelExportTest.StVIPmap")
	proto.RegisterType((*ExcelExportTest_StVIPstruct)(nil), "main.ExcelExportTest.StVIPstruct")
	proto.RegisterType((*ExcelExportTest_StVIPlist)(nil), "main.ExcelExportTest.StVIPlist")
	proto.RegisterType((*Item)(nil), "main.Item")
	proto.RegisterType((*Item_StItemTemplate)(nil), "main.Item.StItemTemplate")
	proto.RegisterType((*Item_StGunWeapon)(nil), "main.Item.StGunWeapon")
	proto.RegisterType((*Item_StAmmunition)(nil), "main.Item.StAmmunition")
	proto.RegisterType((*Item_StAttachment)(nil), "main.Item.StAttachment")
	proto.RegisterType((*Item_StMelleeWeapon)(nil), "main.Item.StMelleeWeapon")
	proto.RegisterType((*Item_StEquipment)(nil), "main.Item.StEquipment")
	proto.RegisterType((*Item_StConsumable)(nil), "main.Item.StConsumable")
	proto.RegisterType((*Item_StThrowable)(nil), "main.Item.StThrowable")
	proto.RegisterType((*Language)(nil), "main.Language")
	proto.RegisterType((*Language_StCommon)(nil), "main.Language.StCommon")
	proto.RegisterType((*Language_StSpecial)(nil), "main.Language.StSpecial")
	proto.RegisterType((*Language_StError)(nil), "main.Language.StError")
}

func init() { proto.RegisterFile("Config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x96, 0x7f, 0x36, 0xb6, 0xc7, 0x89, 0xd3, 0x0e, 0x55, 0x59, 0x56, 0xa8, 0x75, 0x4d, 0x05,
	0x16, 0x42, 0x16, 0x4a, 0x4b, 0xfa, 0x73, 0x01, 0x04, 0x27, 0xb4, 0x56, 0x7f, 0x54, 0x8d, 0x93,
	0x70, 0xcb, 0xd6, 0x99, 0x38, 0xab, 0xee, 0x1f, 0xbb, 0xe3, 0xd0, 0xdc, 0x52, 0xc4, 0xd3, 0x20,
	0x24, 0x1e, 0x05, 0x1e, 0x81, 0x2b, 0xae, 0x78, 0x06, 0x74, 0xce, 0xcc, 0xce, 0xcc, 0xae, 0x9d,
	0x20, 0x44, 0x2f, 0x90, 0xda, 0xab, 0xec, 0xf9, 0xe6, 0x9b, 0x73, 0x66, 0xbe, 0x73, 0xe6, 0xcc,
	0x38, 0x64, 0x7d, 0x9c, 0xc4, 0xc7, 0xc1, 0x7c, 0x94, 0x66, 0x89, 0x48, 0x68, 0x33, 0xf2, 0x83,
	0x78, 0xf0, 0x01, 0x69, 0x3d, 0xc8, 0xfc, 0x28, 0xf2, 0x33, 0xea, 0x92, 0xd6, 0x5c, 0x7e, 0xba,
	0xb5, 0x7e, 0x6d, 0xd8, 0x61, 0x85, 0x39, 0xf8, 0xb5, 0x46, 0x9c, 0x9d, 0x3c, 0xe7, 0x82, 0xbe,
	0x4f, 0x3a, 0xf8, 0x91, 0x3f, 0xe2, 0x67, 0x6e, 0xad, 0xdf, 0x18, 0x3a, 0xcc, 0x00, 0x74, 0x9b,
	0x74, 0xa5, 0x71, 0xe8, 0x87, 0x0b, 0xee, 0xd6, 0xfb, 0x8d, 0x61, 0x77, 0xeb, 0xca, 0x08, 0x02,
	0x8d, 0x70, 0x60, 0x34, 0x15, 0x92, 0xc0, 0x6c, 0xa2, 0xc7, 0x48, 0xbb, 0x18, 0xa0, 0x37, 0xc9,
	0xc6, 0x57, 0xbe, 0x10, 0x21, 0xdf, 0xe5, 0xc7, 0xfe, 0x22, 0x14, 0x6a, 0x2d, 0x65, 0x90, 0xf6,
	0x49, 0xf7, 0x61, 0x12, 0x69, 0x4e, 0x1d, 0x39, 0x36, 0x34, 0x78, 0xd5, 0x23, 0x9b, 0x7b, 0x2f,
	0x67, 0x3c, 0xdc, 0x7b, 0x99, 0x26, 0x99, 0xd8, 0xe7, 0x39, 0xae, 0xfe, 0x70, 0xf2, 0x2c, 0xf2,
	0x53, 0x6b, 0xf5, 0x1a, 0xa0, 0x5f, 0x92, 0xae, 0x34, 0xec, 0xd5, 0x5f, 0x93, 0xab, 0xaf, 0x78,
	0x1a, 0x4d, 0x85, 0xa4, 0x32, 0x7b, 0x0a, 0xfd, 0x02, 0xfd, 0xe7, 0x22, 0x5b, 0xcc, 0x84, 0xdb,
	0xe8, 0xd7, 0x86, 0xdd, 0xad, 0x1b, 0x17, 0xcc, 0x97, 0x44, 0x66, 0xe6, 0xd0, 0x7b, 0xa4, 0x75,
	0x38, 0x79, 0x16, 0x06, 0xb9, 0x70, 0x9b, 0x18, 0xfe, 0xfa, 0x05, 0xd3, 0x81, 0xc6, 0x0a, 0xbe,
	0xf7, 0xaa, 0x09, 0x22, 0xca, 0xd5, 0xc0, 0x46, 0x27, 0xf1, 0x71, 0x32, 0x89, 0xc5, 0xad, 0x2d,
	0x14, 0xd0, 0x61, 0x06, 0xb0, 0x46, 0xb7, 0x6f, 0xa3, 0x74, 0x0d, 0x66, 0x00, 0x28, 0x03, 0x30,
	0xa6, 0x22, 0xc3, 0x2d, 0x74, 0x58, 0x61, 0xd2, 0x0f, 0x49, 0x4f, 0x3b, 0xd9, 0xc9, 0x32, 0xff,
	0x0c, 0x17, 0xe9, 0xb0, 0x0a, 0x6a, 0xf1, 0xb6, 0x6f, 0x4b, 0x9e, 0xd3, 0x6f, 0x0c, 0x1b, 0xac,
	0x82, 0xd2, 0x21, 0xd9, 0x54, 0xae, 0x83, 0x78, 0x2e, 0x89, 0x6b, 0xfd, 0xc6, 0xb0, 0xc3, 0xaa,
	0x30, 0x1d, 0x90, 0xf5, 0x89, 0xe0, 0xd1, 0x38, 0x0c, 0x78, 0x2c, 0x26, 0xbb, 0x6e, 0x0b, 0xb7,
	0x54, 0xc2, 0xe8, 0x47, 0xa4, 0x35, 0x4e, 0xe2, 0x7c, 0x11, 0x71, 0xb7, 0x8d, 0xd2, 0x6f, 0x48,
	0xed, 0x54, 0x79, 0xb3, 0x62, 0x94, 0x5e, 0x23, 0x64, 0x2f, 0x4a, 0xc5, 0x99, 0x54, 0xa7, 0x83,
	0xae, 0x2c, 0xc4, 0x1e, 0xdf, 0xbe, 0xed, 0x12, 0xd4, 0xc7, 0x42, 0xa8, 0x47, 0xda, 0x68, 0x81,
	0x42, 0x5d, 0x54, 0x48, 0xdb, 0xb0, 0x25, 0xe3, 0x49, 0x6e, 0x69, 0x1d, 0x35, 0xaa, 0xc2, 0x36,
	0xb3, 0x50, 0x69, 0x03, 0x55, 0xaa, 0xc2, 0xf4, 0x63, 0x72, 0xa9, 0xf0, 0xaf, 0x75, 0xea, 0xa1,
	0x4e, 0x4b, 0xb8, 0xf7, 0x53, 0x93, 0x74, 0xad, 0xda, 0x7a, 0x5b, 0x08, 0x6f, 0x6a, 0x21, 0xfc,
	0xd8, 0x24, 0x1d, 0xdd, 0x25, 0xde, 0x96, 0xc1, 0x1b, 0x5a, 0x06, 0x83, 0x1f, 0xae, 0x92, 0x26,
	0xa8, 0x82, 0xda, 0x0a, 0x1e, 0xed, 0xf3, 0x28, 0x0d, 0x7d, 0xc1, 0xcd, 0x05, 0x58, 0x85, 0xe9,
	0x03, 0x72, 0xd9, 0x86, 0xec, 0xcb, 0xf0, 0x3d, 0xa9, 0x20, 0x0c, 0x8f, 0xa6, 0xc2, 0x66, 0xb1,
	0xe5, 0x39, 0x90, 0xa4, 0x07, 0x8b, 0xf8, 0x1b, 0xee, 0xa7, 0x49, 0x0c, 0xf1, 0x1a, 0x18, 0xaf,
	0x84, 0xd1, 0xcf, 0x49, 0x4f, 0xdb, 0x32, 0x92, 0xbc, 0xf7, 0xae, 0x96, 0x22, 0x69, 0x0a, 0xab,
	0xb0, 0xe1, 0xb5, 0xb0, 0x13, 0x45, 0x8b, 0x38, 0x10, 0x81, 0x0c, 0xe2, 0x60, 0x90, 0x32, 0x48,
	0x77, 0xc8, 0xa6, 0x01, 0x64, 0x98, 0x35, 0x0c, 0xf3, 0x6e, 0x29, 0x8c, 0xe1, 0xb0, 0x2a, 0x1f,
	0x03, 0x09, 0xe1, 0xcf, 0x4e, 0x22, 0x1e, 0x0b, 0x08, 0xd4, 0x52, 0x81, 0x6c, 0x10, 0x03, 0x69,
	0x40, 0x06, 0x6a, 0xaf, 0x0a, 0xa4, 0x39, 0xac, 0xca, 0x87, 0x44, 0x3d, 0xe1, 0x61, 0xc8, 0xb9,
	0x11, 0xae, 0x23, 0x13, 0x55, 0x81, 0x21, 0x51, 0x36, 0x24, 0xc3, 0x91, 0x15, 0x89, 0xb2, 0x59,
	0x6c, 0x79, 0x0e, 0x24, 0x6a, 0xef, 0xbb, 0x45, 0x90, 0x16, 0x5b, 0xeb, 0xca, 0x44, 0xd9, 0x18,
	0x24, 0x4a, 0xdb, 0x32, 0xd2, 0xfa, 0x8a, 0x44, 0x69, 0x0a, 0xab, 0xb0, 0x41, 0x3f, 0x79, 0xde,
	0xfc, 0xe7, 0x21, 0x56, 0xdf, 0x86, 0xd4, 0xaf, 0x04, 0x82, 0x7e, 0x06, 0x90, 0x61, 0x7a, 0x2b,
	0xf4, 0x33, 0x1c, 0x56, 0xe5, 0xc3, 0x66, 0xf6, 0x4f, 0xb2, 0xe4, 0xfb, 0x22, 0xce, 0xa6, 0xdc,
	0x8c, 0x8d, 0xc1, 0x66, 0xb4, 0x2d, 0xa3, 0x5c, 0x5a, 0xb1, 0x19, 0x4d, 0x61, 0x15, 0xb6, 0xf7,
	0x73, 0x8d, 0xf4, 0xca, 0xf5, 0x4f, 0x29, 0x69, 0x3e, 0xf5, 0x23, 0xae, 0x5e, 0xab, 0xf8, 0x0d,
	0xd8, 0x2e, 0xcf, 0x67, 0xea, 0x75, 0x8a, 0xdf, 0xd0, 0x4d, 0xf1, 0xa1, 0x3b, 0xd9, 0xc5, 0x6e,
	0xea, 0xb0, 0xc2, 0x84, 0x36, 0x33, 0x99, 0x25, 0xf1, 0xd3, 0x24, 0x8b, 0xfc, 0xd0, 0x6d, 0xe2,
	0x1c, 0x0b, 0xc1, 0x2e, 0x3d, 0x4b, 0xe2, 0xc7, 0x7e, 0x36, 0xe7, 0xae, 0x83, 0xc3, 0x06, 0x80,
	0x26, 0x84, 0xeb, 0x39, 0x4b, 0xa1, 0xb6, 0xc1, 0xb1, 0xb6, 0xbd, 0xdf, 0xeb, 0xf0, 0x28, 0xd0,
	0x27, 0x07, 0x72, 0xa1, 0x0d, 0x9c, 0x20, 0x6f, 0x84, 0x32, 0x08, 0xf1, 0xa6, 0x27, 0x49, 0x22,
	0x9e, 0x24, 0x47, 0xf2, 0xfc, 0x3b, 0xcc, 0x00, 0xd0, 0xd3, 0xcd, 0x11, 0x41, 0x27, 0x72, 0x3b,
	0x15, 0x14, 0xca, 0xd9, 0x54, 0x38, 0x20, 0xb9, 0xba, 0x24, 0xaa, 0x30, 0xbd, 0x43, 0x9c, 0x1d,
	0x21, 0xb2, 0x1c, 0x8f, 0xb0, 0x7e, 0x38, 0x57, 0x3b, 0xc0, 0x08, 0x39, 0x7b, 0xb1, 0xc8, 0xce,
	0x98, 0xe4, 0xc3, 0xd6, 0xf1, 0x03, 0xb2, 0xbd, 0x86, 0xbe, 0xb5, 0x0d, 0xa2, 0xe2, 0xb7, 0xcc,
	0xb2, 0x3c, 0xb3, 0x16, 0xe2, 0xdd, 0x55, 0xe3, 0xe8, 0x90, 0x5e, 0x22, 0x8d, 0x17, 0xd8, 0x18,
	0x61, 0x27, 0xf0, 0x49, 0xaf, 0x10, 0xe7, 0x54, 0x35, 0x40, 0xc0, 0xa4, 0x71, 0xbf, 0x7e, 0xb7,
	0xe6, 0x7d, 0x4b, 0xd6, 0xed, 0x8e, 0xb1, 0x42, 0x90, 0xda, 0xb9, 0x82, 0x68, 0x64, 0x2a, 0xfc,
	0xd9, 0x0b, 0xe5, 0xbb, 0x0a, 0x7b, 0x7f, 0x36, 0x30, 0x84, 0x96, 0x09, 0x43, 0x94, 0x44, 0xd3,
	0x21, 0x4a, 0x28, 0x6c, 0x5a, 0xeb, 0x95, 0xab, 0xd4, 0x59, 0x88, 0xcc, 0xec, 0x42, 0x4c, 0x93,
	0x45, 0x7c, 0xa4, 0xd2, 0x66, 0x00, 0x90, 0x13, 0x8c, 0xaf, 0x83, 0x8c, 0x63, 0x15, 0x3a, 0x4c,
	0xdb, 0xf4, 0x6e, 0x39, 0x47, 0x83, 0x73, 0xba, 0xda, 0xeb, 0x4d, 0x12, 0xfd, 0x8c, 0x34, 0xc7,
	0x61, 0x90, 0xaa, 0x56, 0x7a, 0xe3, 0xbc, 0xa0, 0xc0, 0x91, 0x31, 0x91, 0x0e, 0x47, 0x0d, 0xfe,
	0x9a, 0x0e, 0x5a, 0x98, 0x20, 0x00, 0x7c, 0x9a, 0x8e, 0xe9, 0x30, 0x03, 0xfc, 0x87, 0x9a, 0xb8,
	0x23, 0xfd, 0xfe, 0xfb, 0x89, 0x7f, 0x61, 0x43, 0xb1, 0x3b, 0x33, 0xdc, 0xf2, 0xb6, 0x6d, 0xa5,
	0x7b, 0x09, 0xa7, 0xf7, 0x8b, 0xb4, 0xc8, 0x6b, 0xfa, 0xe6, 0xb9, 0xdd, 0xff, 0x1f, 0x12, 0xd3,
	0xb8, 0x30, 0x31, 0xcd, 0xd7, 0x78, 0x7a, 0xfe, 0xa8, 0x41, 0x4b, 0xd2, 0x77, 0x04, 0xb4, 0x24,
	0x6d, 0xd8, 0x2d, 0xa9, 0x04, 0x9a, 0x16, 0x51, 0x5f, 0x51, 0x09, 0x9a, 0xfa, 0xbf, 0xd9, 0xe4,
	0x2f, 0x75, 0x38, 0xc0, 0xe6, 0x82, 0x82, 0x03, 0x6c, 0x2c, 0xfb, 0x00, 0x97, 0x51, 0xa8, 0xdc,
	0x83, 0x9c, 0xef, 0x07, 0x51, 0xe1, 0xb4, 0x30, 0x61, 0xb1, 0x07, 0x39, 0x7f, 0x98, 0x3e, 0x0e,
	0xa2, 0x40, 0xa8, 0xb3, 0x6b, 0x21, 0x6a, 0x9c, 0xf1, 0x59, 0x72, 0xca, 0x33, 0x75, 0x7c, 0x2d,
	0x84, 0x7e, 0x42, 0x2e, 0x1b, 0xeb, 0x40, 0xb9, 0x71, 0x90, 0xb6, 0x3c, 0x00, 0xb2, 0x3d, 0xe2,
	0x3c, 0xc5, 0x85, 0xa8, 0x4b, 0xa5, 0xb0, 0xe9, 0xa7, 0xe4, 0x1d, 0xf8, 0x56, 0x33, 0x26, 0xb1,
	0xe0, 0xd9, 0xa9, 0x1f, 0xaa, 0x97, 0xf8, 0xaa, 0x21, 0xda, 0x27, 0x5d, 0x0b, 0xc6, 0x47, 0xb9,
	0xc3, 0x6c, 0xc8, 0x3b, 0x80, 0xa2, 0xd0, 0x77, 0x2d, 0x14, 0x85, 0x36, 0xec, 0xa2, 0x28, 0x81,
	0xe0, 0x96, 0xf9, 0x47, 0xc1, 0x22, 0x1f, 0x87, 0x49, 0x5e, 0x08, 0x66, 0x43, 0x83, 0xdf, 0xea,
	0xa4, 0xfd, 0xd8, 0x8f, 0xe7, 0x0b, 0x7f, 0x8e, 0xd7, 0xda, 0x38, 0x89, 0x22, 0xf9, 0xb2, 0xaa,
	0xe1, 0xb3, 0xd9, 0x00, 0xf4, 0x1e, 0xe9, 0x4a, 0xc3, 0x7e, 0xf6, 0xaa, 0xc7, 0x47, 0xe1, 0x02,
	0x1f, 0x20, 0xc0, 0x61, 0x36, 0x97, 0x6e, 0x91, 0xd6, 0x34, 0xe5, 0xb3, 0xc0, 0x0f, 0xb1, 0xc4,
	0xba, 0x5b, 0xee, 0xd2, 0x34, 0x35, 0xce, 0x0a, 0x22, 0xfe, 0x74, 0xc8, 0xb2, 0x24, 0x83, 0xb5,
	0x34, 0x71, 0x2d, 0xda, 0xa6, 0xdb, 0x84, 0xe0, 0xb7, 0x5c, 0x89, 0x63, 0x3f, 0x50, 0x2c, 0x97,
	0x48, 0x61, 0x16, 0xd3, 0xeb, 0x93, 0x76, 0xb1, 0x40, 0xa8, 0x4d, 0x39, 0x5d, 0x3e, 0x4b, 0xa4,
	0xe1, 0xdd, 0x80, 0x9f, 0x86, 0xc5, 0x12, 0x56, 0x53, 0xae, 0x93, 0x96, 0xf2, 0xbd, 0x9a, 0xf0,
	0x7c, 0x0d, 0xff, 0x89, 0x78, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0x55, 0xa8, 0xdc,
	0x54, 0x14, 0x00, 0x00,
}
